### ISSUE TITLE
autoplot of rda showing only sites error 

### ISSUE THREAD

**Issue by richardjtelford** [gavinsimpson/ggvegan#21]
```
 sol <- rda(dune)
 autoplot(sol, layers = "sites")
>Error: Aesthetics must be either length 1 or the same as the data (1): xend, yend
```
Works fine in `arrows = FALSE`

**Comment by gavinsimpson** [comment]
Thanks @richardjtelford. I think I have this fixed in `autoplot.rda()`, by mostly rewriting the logic for how things get plotted as the current version is a mess and wrong. But similar issues probably plague other methods too. I just need to generalise one element of the fixed version into something I can reuse in other functions and then I can push a fix here.
