### ISSUE TITLE
autoplot.rda argument const is ignored

### ISSUE THREAD

**Issue by richardjtelford** [gavinsimpson/ggvegan#26]
```
data(dune)
m <- rda(dune)
plot(m)
plot(m, const = c(2, 1)) # changes arrow length

autoplot(m)
autoplot(m, const = c(2, 1)) # no change in arrow length
```
The solution is either to remove the `const` argument so that `const` can be passed with the `...` or to pass `const` to `fortify.rda`.

**Comment by richardjtelford** [comment]
There is also a const argument to autoplot.cca which makes no difference to (scores are identical). 

```
data(dune)
data("dune.env")
CA <- cca(dune)
identical(scores(CA), scores(CA, const = c(2, 1)))

CCA <- cca(dune ~ ., dune.env)
identical(scores(CCA),
          scores(CCA, const = c(2, 1)))
```
Perhaps the `const` argument to `autoplot.cca` can be removed

**Comment by gavinsimpson** [comment]
Thanks Richard. I think it is probably best to remove `const` from the arguments for both `autoplot.rda` and `autoplot.cca`. In the former, as you say, it could be passed via `...` if needed and in the latter it is ignored (silently - which is bad).

Whether to remove it or not will depend on whether this is too esoteric an argument to devote attention to in *ggevegan*?

If we keep it, should it be renamed so that the argument is more meaningful?

**Comment by richardjtelford** [comment]
I agree that it is probably best to remove `const` from both `autoplot.rda` and `autoplot.cca`. I have never used this argument before (but there have been a few times when it might have been useful had I found it). If needed, the help for `...` could be expanded to give examples of useful arguments in `scores`.

The argument name is not great, but it is consistent with `vegan`. Whether it should be renamed there is another question.

**Comment by gavinsimpson** [comment]
Thanks @richardjtelford I decided to keep the `const` argument in `autoplot.rda` but pass it along now as you suggested.
