### ISSUE TITLE
Recreating autoplot.cca() from fortify.cca() data frame

### ISSUE THREAD

**Issue by padpadpadpad** [gavinsimpson/ggvegan#9]
Hi Gavin

As ever a very cool package. I am trying to help a student plot a cca using ggvegan and wanted a little more control over the ggplot2 object returned so was trying to `fortify()` the data and then create the plot object.

However, when I plot the predictor variables (the arrows) of the fortify data frame (`Score == 'biplot'`), the arrows do not look quite like the output of autoplot().

I use the code:

``` r
ggplot() +
    geom_segment(data = subset(d, Score == "biplot"), aes(x = 0, y = 0, xend = Dim1, yend = Dim2), arrow = arrow(length = unit(0.01, "npc"))
```
To plot the arrows and they do not fill the same space as in the autoplot. The plot using ggplot sets limits equal to the dimensions of the data frame, whereas autoplot() gives different results.

Autoplot example:
[Autoplot.pdf](https://github.com/gavinsimpson/ggvegan/files/1510587/Good_legend.pdf)

Ggplot only example:
[Ggplot.pdf](https://github.com/gavinsimpson/ggvegan/files/1510588/Rplot.pdf)

Just wondering if this difference (a) is important and (b) how to get from one to the other reproducibly.

Many thanks
Dan

**Comment by gavinsimpson** [comment]
Ordination diagrams need to have a fixed aspect ratio because the Euclidean distance on the plot is directly (or closely, but not perfectly, depending on scalings) related to some method-specific measure of dissimilarity. On a CCA, distances on the plot are related to the chi-square distance between samples.

To set this up in **ggplot** we need to use `coord_equal()` or `coord_fixed()`. For example (using the newer version of **ggvegan**, which changes a little how the scores are returned via `fortify()`:

```r
library('vegan')
library('ggvegan')
data(varespec, varechem)

ord <- cca(varespec ~ Al + P*(K + Baresoil), data=varechem)
```

The `autoplot()` method produces

```r
autoplot(ord)
```

![cca-autoplot](https://user-images.githubusercontent.com/514696/33330806-7e623174-d425-11e7-894a-62aab9052f2e.png)

To recreate this, but just showing the biplot arrows we would do the following

```r
ford <- fortify(ord, axes = 1:2)
take <- c('CCA1', 'CCA2')
arrows <- subset(ford, Score == 'biplot')
mul <- ggvegan:::arrowMul(arrows[, take],
                          subset(ford, select = take, Score == 'sites'))
arrows[, take] <- arrows[, take] * mul

ggplot() +
  geom_point(data = subset(ford, Score == 'sites'),
             mapping = aes(x = CCA1, y = CCA2)) + 
  geom_segment(data = arrows,
             mapping = aes(x = 0, y = 0, xend = CCA1, yend = CCA2),
             arrow = arrow(length = unit(0.01, "npc"))) +
  geom_text(data = arrows, # crudely push labels away arrow heads
             mapping = aes(label = Label, x = CCA1 * 1.1, y = CCA2 * 1.1)) +
  coord_fixed()
```

This gives

![cca-manual](https://user-images.githubusercontent.com/514696/33332148-168999b2-d429-11e7-8c06-877894edd7e5.png)

If you want to include more scores in the plot, then the multiplier line needs to be:
```r
mul <- ggvegan:::arrowMul(arrows[, take],
                          subset(ford, select = take, Score %in% c('sites')))
```
and add extra score types to the RHS of `%in%`.

**Comment by padpadpadpad** [comment]
Thanks Gavin

This is a fantastically reproducible example given the lack of reproducibility in my question. 

Cannot really add anything in here...

I have fiddled with your plot function:

```r
ggplot() +
  geom_point(data = subset(ford, Score == 'sites'),
             mapping = aes(x = CCA1, y = CCA2)) + 
  geom_segment(data = arrows,
               mapping = aes(x = 0, y = 0, xend = CCA1, yend = CCA2),
               arrow = arrow(length = unit(0.01, "npc"))) +
  geom_text(data = arrows,
            mapping = aes(label = Label, x = CCA1, y = CCA2, hjust = 0.5*(1 - sign(CCA1)), vjust = 0.5*(1-sign(CCA2)))) +
  coord_fixed() +
  scale_x_continuous(expand = c(.1, .1)) +
  scale_y_continuous(expand = c(.1, .1))
```

This will now always (if my code is right) keep labels away from arrow heads and the scale_x and scale_y_continuous will increase the axis spaces if your labels are quite long and at the edge of the plot space.

Thanks again Gavin. I really appreciate your help (and everything you do for the multivariate ecological community).

Cheers
Dan
